[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'Frontend already built, skipping build phase'"]

[start]
cmd = "npm start"
