#!/bin/bash

echo "🚀 STEP 2: Railway.app Deployment Guide"
echo "========================================"
echo ""

echo "📋 Prerequisites Check:"
echo "✅ Code pushed to GitHub"
echo "✅ Railway.json configured"
echo "✅ Server.js updated for production"
echo "✅ Environment files created"
echo ""

echo "🌐 RAILWAY DEPLOYMENT STEPS:"
echo ""

echo "1️⃣ CREATE RAILWAY PROJECT:"
echo "   • Go to https://railway.app"
echo "   • Click 'New Project'"
echo "   • Select 'Deploy from GitHub repo'"
echo "   • Choose your 'chat-app' repository"
echo "   • Railway will detect Node.js app automatically"
echo ""

echo "2️⃣ ADD MONGODB DATABASE:"
echo "   • In Railway dashboard, click '+ New Service'"
echo "   • Select 'Database' → 'MongoDB'"
echo "   • Railway will create a MongoDB instance"
echo "   • Copy the connection string from Database tab"
echo ""

echo "3️⃣ CONFIGURE ENVIRONMENT VARIABLES:"
echo "   • Go to your service → 'Variables' tab"
echo "   • Add these variables:"
echo ""
echo "   🔹 Required Variables:"
echo "   NODE_ENV=production"
echo "   PORT=\$PORT (Railway sets this automatically)"
echo "   MONGO_URL=[Copy from MongoDB service]"
echo "   JWT_SECRET=your-super-secure-jwt-secret-key-here"
echo ""
echo "   🔹 Email Variables (for OTP features):"
echo "   EMAIL_USER=your-email@gmail.com"
echo "   EMAIL_PASS=your-app-password"
echo ""
echo "   🔹 Frontend Variables (if serving separately):"
echo "   REACT_APP_API_URL=https://your-app.railway.app"
echo "   REACT_APP_SOCKET_URL=https://your-app.railway.app"
echo "   REACT_APP_LOCALHOST_KEY=chat-app-current-user"
echo "   REACT_APP_DEMO_MODE=true"
echo ""

echo "4️⃣ DEPLOY THE APPLICATION:"
echo "   • Railway will auto-deploy when you push to GitHub"
echo "   • Monitor deployment in 'Deployments' tab"
echo "   • Check logs for any errors"
echo ""

echo "5️⃣ TEST THE DEPLOYMENT:"
echo "   • Visit your Railway app URL"
echo "   • Test user registration/login"
echo "   • Test real-time messaging"
echo "   • Test file uploads"
echo "   • Test video calls"
echo ""

echo "6️⃣ SEED DEMO DATA (Optional):"
echo "   • SSH into Railway container or"
echo "   • Add seed endpoint to create demo users"
echo ""

echo "🎯 POST-DEPLOYMENT CHECKLIST:"
echo "□ App loads correctly"
echo "□ User registration works"
echo "□ Real-time messaging works"
echo "□ File uploads work"
echo "□ Video calls connect"
echo "□ Database persists data"
echo "□ Demo accounts created"
echo ""

echo "📝 UPDATE README WITH LIVE URL:"
echo "Once deployed, update your README.md with:"
echo "• Live Demo URL: https://your-app.railway.app"
echo "• Demo credentials"
echo "• Any known limitations"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo "• Check Railway logs for errors"
echo "• Verify all environment variables are set"
echo "• Ensure MongoDB connection string is correct"
echo "• Check CORS settings for production domain"
echo ""

echo "✅ Your ChatFlow app will be production-ready!"
echo "📧 Ready for interviewer demo access!"
