name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      run: |
        cd server
        npm ci

    - name: Install Frontend Dependencies
      run: |
        cd public
        npm ci

    - name: Run Backend Tests
      run: |
        cd server
        npm run test --if-present

    - name: Run Frontend Tests
      run: |
        cd public
        npm run test --if-present

    - name: Build Frontend
      run: |
        cd public
        npm run build

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Images
      run: |
        docker-compose build

    - name: Test Docker Containers
      run: |
        docker-compose up -d
        sleep 30
        docker-compose down
